### PR TITLE
Fix #32 try to use findPnpApi to locate pnpapi

### LINKED ISSUE #32: pnp-webpack-plugin cannot work outside of pnp runtime.
## Context
Trying to add yarn pnp support to cypress and ran into following error
```
**Details:** Error: Cannot find module 'pnpapi'
Require stack:
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/pnp-webpack-plugin/index.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-batteries-included-preprocessor/index.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
Require stack:
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/pnp-webpack-plugin/index.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-batteries-included-preprocessor/index.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.external_module_.Module._resolveFilename (/Users/mluo/workspace/gitlab/ui-platform/projects/apps/px/.pnp.js:38306:54)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at external_module_.Module._load (/Users/mluo/workspace/gitlab/ui-platform/projects/apps/px/.pnp.js:38162:36)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getSourceLocation (/Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/pnp-webpack-plugin/index.js:39:15)
    at makeResolver (/Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/pnp-webpack-plugin/index.js:53:26)
    at Object.<anonymous> (/Users/mluo/Library/Caches/Cypress/6.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/pnp-webpack-plugin/index.js:147:10)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at external_module_.Module._load (/Users/mluo/workspace/gitlab/ui-platform/projects/apps/px/.pnp.js:38162:36)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
```

Cypress server (an Electron app)is forking a new process to compile plugins from user project, however, the webpack config and compile code live with Cypress app. 

After chatting with merceyz in channel, it looks like pnp-webpack-plugin assumes it been located within the pnp project and it's not the case here.

https://discord.com/channels/226791405589233664/654372321225605128/822584013377241108

Would that be possible to port what we've done in webpack 5/enhanced-resolve so pnp-webpack-plugin can work in that scenario.

### PR DESCRIPTION
**Pull request by missing1984**
## Context
The current implementation assume `pnp-webpack-plugin` live within the current pnp runtime. It's not true when webpack live outside of the pnp runtime and used to build pnp projects. 

It's a rare cases but Cypress uses this pattern to built its plugin.  Make pnp-webpack-plugin work with other pnp runtime is the first step to unblock yarn2 support in Cypress.

## Solution
Switch to use `findPnpApi` to locate pnp api first and fallback to require('pnpapi') if `findPnpApi` failed to locate the api.

## Effects
Fixes #32 

The fix should be compatible with no breaking change

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -36,7 +60,9 @@ function getSourceLocation(sourceLocator) {
   if (!sourceLocator)
     return null;
 
-  const pnp = require(`pnpapi`);
+  const pnp = getPnpApi();
+  if (!pnp) 
+    return null;
```
Comment (arcanis) [inline index.js:65]: Doesn't that risk being a problem, if it just always return the main process' API?

**Comment by arcanis** [comment]
I feel like this approach is a bit risky (for your use case), because different functions may end up using different instances of the API. Instead, I think an ideal approach might be to retrieve the right PnP API when instantiating the plugin, and passing it around as parameter (instead of them relying on the global `pnpapi` variable). Does that make sense?

**Comment by missing1984** [comment]
that works too but we need to refactor the apis which will be a breaking change..

so basically.

from 
```
function makeResolver(sourceLocator, filter) {
  const sourceLocation = getSourceLocation(sourceLocator);
 const pnpApi = require('pnpapi')
```
to something like
```
function makeResolver(sourceLocator, filter, opts) {
    const sourceLocation = getSourceLocation(sourceLocator, opts);
    const api = opts.pnpApi? opts.pnpApi: require('pnpapi'); // or take a path that can be used to fetch pnpapi.
}
```
the default export as well as other exports that immediately get invoked needs to be change to a function so consumer can pass the pnpapi or path when initialize the plugin.

does that sounds right?

**Comment by missing1984** [comment]
I've refactored the code a bit.

1.  Move `makeResolver` function to a `./resolver` file and refactored its interface to accept a pnpapi instance.
2. Refactor all exports from index.js to use the new `makeResolver` function with a resolved pnpapi instance.

There will be no breaking change to the existing user.. and i can use the `makeResolver` function to construct a new Webpack plugin for my use case.. for example.

```typescript
/**
 * Config yarn pnp plugin for webpack 4
 * @param {*} file file to be processed
 * @param {*} options 
 */
const addYarnPnpConfig = (file, options) => {
  const { makeResolver } = require('pnp-webpack-plugin/resolver');
  const findPnpApi = require('module').findPnpApi;
  if (findPnpApi && file.filePath) {
    const pnpapi = findPnpApi(file.filePath);
    console.log(`addYarnPnpConfig pnpapi`, pnpapi);
    const PnpPlugin = {
      apply: makeResolver({pnpapi})
    }
    options.webpackOptions.resolve.plugins.push(PnpPlugin);
  }
}

```
The tradeoff would be a new `pnp-webpack-plugin/resolver` module that we need to maintain.  I think it should be fine as we're moving to webpack 5 anyway.

**Comment by missing1984** [comment]
@arcanis any updates on this?
